name: Build Next.js App

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                default: '.'

jobs:
    build:
        runs-on: [ubuntu-latest]
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}
        steps:
            - uses: actions/checkout@v4 # Check out the repository code
            - uses: actions/setup-node@v4 # Set up Node.js environment
              with:
                  node-version: '22' # Specify Node.js version
                  cache: 'npm' # Cache npm dependencies for speed
                  cache-dependency-path: '${{ inputs.working-directory }}/package-lock.json'
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.npm
                      ${{ github.workspace }}/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - name: Install dependencies
              # run: npm ci # Install dependencies (faster than npm install)
              run: npm install # Install dependencies (we use this temporarily because `npm ci` does not work for some reason)
            - name: Build
              env:
                  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_TOKEN }}
              run: npm run build # Build the app
            - name: Test
              run: npm run test # Test the app
