name: 'Build automatically'

on:
    push:
        branches: ['main']
        paths-ignore:
            - '.github/workflows/**'
            - '!.github/workflows/build.yml'
            - '**/readme.md'
    pull_request:
        branches: ['main']
        paths-ignore:
            - '.github/workflows/**'
            - '!.github/workflows/build.yml'
            - '**/readme.md'
jobs:
    build:
        uses: ./.github/workflows/build.yml
